### PR TITLE
Workloadmanager selective

### PR DESCRIPTION
**Pull request by agrass15268**
## Description
Goal: to improve the selection of workload-managers (WM) as discussed in PR #59.

Instead of simply choosing a file according to its prefix, the settings for workload-managers have been outsourced to two new files in /bin/, slurm-preamble.sh and SGE-preamble.sh. 

These are still selected according to their prefixes and contain the instructions for workload managers. Their content is simply prepended to the copied simulation.sh and simulation_charmm.sh files.

To that end, a new private function (_write_workload_preamble) was added to state.py.

This is **not** exactly the same solution as in PR #59, as that would have still required 8 files (due to needing charmm/openmm separation or argument switches). 

This should be easily extendable to new WMs (requiring modification of the possible WMs in utils.py and a *-preamble.sh file) and MD engines (requiring a call to _write_workload_preamble after the submit file has been copied.)

All references to the old system were removed from state.py.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] Reduced number of files necessary from 8 to 6
  - [x] Local changes to the preamble file are applied across all simulations and do not require an edit to each file
  - [x] Only one version of the simulation scripts to maintain 

## Status

Test builds of both slurm and SGE deliver the expected results on my side. I'd like to request @JohannesKarwou to run the full suite or whatever he deems necessary to ensure compatibility.

### CODE REVIEW

**Review by wiederm — APPROVED** [review]
Perfect! Thank you very much, that looks great!

**Comment by JohannesKarwou** [comment]
@agrass15268 for me it does not work, it seems if one wants to use calculate rsfe one gets the preamble of slurm but the rest of SGE

**Comment by JohannesKarwou** [comment]
> > @agrass15268 for me it does not work, it seems if one wants to calculate rsfe with slurm one gets the preamble of slurm but the rest of SGE
> 
> I'm somewhat confused - that is the intended behaviour? Or rather, what do you mean with "the rest of SGE" - besides the preamble, the files are identical (and SGE-simulation-rsfe.sh no longer exists, so cannot be included).
> 
> The only thing i could think of is that the /build/ folder still contains the old files - could you try deleting it, running `python setup.py install` again and see if the problem persists?

Ok sorry your right, I had an internal problem :) Everything works fine

**Comment by agrass15268** [comment]
Ok, so since this is resolved and tests are all positive now- @JohannesKarwou apparently cannot merge this despite the review, and I obviously don't have any rights whatsoever. So if you would be so kind as to merge @wiederm? Regarding the merge conflict - that file can simply be deleted, it no longer exists.

**Comment by wiederm** [comment]
thanks! I resolved the conflict and merged!

**Pull request merged**
